config/routes.rb
Rails.application.routes.draw do
  resources :post_images, only: [:new, :create, :index, :show, :destroy] do
    resource :favorite, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end
  # ユーザー登録（サインアップ）のためのルーティングを追加
  resources :users, only: [:new, :create, :show, :edit, :update] , path_names: { new: 'sign_up' }
  
  get "homes/about", to: "homes#about", as: "about"
  resource :session
  resources :passwords, param: :token
  root to: "homes#top"
end

app/models/post_image.rb
class PostImage < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :shop_name, presence: true
  validates :image, presence: true

  def get_image
    if image.attached?
      image
    else
      "no_image.jpg"
    end
  end

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
end

app/controllers/post_images_controller.rb
class PostImagesController < ApplicationController

  def new
    @post_image = PostImage.new
  end
  
    # 投稿データの保存
  def create
    @post_image = PostImage.new(post_image_params)
    @post_image.user_id = Current.user.id
    if @post_image.save
      redirect_to post_images_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def index
    @post_images = PostImage.page(params[:page])
  end

  def show
    @post_image = PostImage.find(params[:id]) 
    @post_comment = PostComment.new
  end

  def destroy
    post_image = PostImage.find(params[:id]) 
    post_image.destroy
    redirect_to post_images_path
  end


    # 投稿データのストロングパラメータ
  private

  def post_image_params
    params.require(:post_image).permit(:shop_name, :image, :caption)
  end
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/views/post_images/_list.html.erb
<div class="container py-5">
  <% post_images.each do |post_image| %>
    <div class="card mb-4 shadow-sm mx-auto" style="max-width: 600px;">
      <%= link_to post_image_path(post_image.id) do %>
        <%= image_tag post_image.get_image, class: "card-img-top" %>
      <% end %>

      <div class="card-body">
        <div class="d-flex align-items-center mb-3">
          <%= image_tag post_image.user.get_profile_image(60, 60), class: "rounded-circle me-3 img-fluid" %>
          <strong><%= post_image.user.name %></strong>
        </div>

        <p class="mb-1"><strong>ショップ名：</strong><%= post_image.shop_name %></p>
        <p class="mb-2"><strong>説明：</strong><%= post_image.caption %></p>
        <p class="text-muted mb-0"><%= link_to "#{post_image.post_comments.count} コメント", post_image_path(post_image.id), class: "text-decoration-none text-dark" %></p>
      </div>
    </div>
  <% end %>

  <div class="d-flex justify-content-center mt-4">
    <%= paginate post_images %>
  </div>
</div>

app/views/post_images/index.html.erb
<%= render 'list', post_images: @post_images %>

app/views/post_images/new.html.erb
<div class="container my-5">
  <div class="row justify-content-center">
    <div class="col-md-6 shadow-lg rounded px-0">
      <h5 class="text-dark bg-light p-4 mb-0">画像投稿フォーム</h5>
      <div class="p-4">
        <% if @post_image.errors.any? %>
          <div class="alert alert-danger" role="alert">
            <h6 class="alert-heading"><%= @post_image.errors.count %>件のエラーが発生しました</h6>
            <ul class="mb-0">
              <% @post_image.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <%= form_with model: @post_image, local: true do |f| %>
          <!-- 画像 -->
          <div class="mb-3">
            <label class="form-label fw-bold">画像</label>
            <%= f.file_field :image, accept: "image/*", class: "form-control" %>
          </div>

          <!-- ショップ名 -->
          <div class="mb-3">
            <label class="form-label fw-bold">ショップ名</label>
            <%= f.text_field :shop_name, class: "form-control", placeholder: "ショップ名を入力" %>
          </div>

          <!-- 説明 -->
          <div class="mb-3">
            <label class="form-label fw-bold">説明</label>
            <%= f.text_area :caption, rows: 3, class: "form-control", placeholder: "コメントを入力" %>
          </div>

          <!-- 送信ボタン -->
          <div class="d-grid mt-4">
            <%= f.submit "投稿", class: "btn btn-info btn-lg text-white" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/post_images/show.html.erb
<div>
  <%= image_tag @post_image.get_image %>
  <p>ショップ名：<%= @post_image.shop_name %></p>
  <p>説明：<%= @post_image.caption %></p>
  <p>投稿ユーザー画像：<%= image_tag @post_image.user.get_profile_image(100,100) %></p>
  <p>ユーザーネーム：<%= @post_image.user.name %></p>
  <p>投稿日：<%= @post_image.created_at.strftime('%Y/%m/%d') %></p>
  <% if @post_image.user == Current.user %>
    <%= link_to "削除", post_image_path(@post_image), data: { turbo_method: :delete } %>
  <% end %>
  <% if @post_image.favorited_by?(Current.user) %>
    <p>
      <%= link_to post_image_favorite_path(@post_image), data: { turbo_method: :delete } do %>
        ♥<%= @post_image.favorites.count %> いいね
      <% end %>
    </p>
    <% else %>
    <p>
      <%= link_to post_image_favorite_path(@post_image), data: { turbo_method: "post" } do %>
        ♡<%= @post_image.favorites.count %> いいね
      <% end %>
    </p>
  <% end %>
</div>

<div>
  <p>コメント件数：<%= @post_image.post_comments.count %></p>
  <% @post_image.post_comments.each do |post_comment| %>
    <p><%= image_tag post_comment.user.get_profile_image(100,100) %></p>
    <%= post_comment.user.name %>
    <%= post_comment.created_at.strftime('%Y/%m/%d') %><%= post_comment.comment %>
    <% if post_comment.user == Current.user %>
      <%= link_to "削除", post_image_post_comment_path(post_comment.post_image, post_comment), data: { turbo_method: :delete } %>
    <% end %>
  <% end %>
</div>
<div>
  <%= form_with model: [@post_image, @post_comment] do |f| %>
    <%= f.text_area :comment, rows: '5', placeholder: "コメントをここに" %>
    <%= f.submit "送信する" %>
  <% end %>
</div>